import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('English');

    const languages = [
        "English", "Mandarin Chinese", "Hindi", "Spanish", "French",
        "Arabic", "Bengali", "Portuguese", "Russian", "Urdu",
        "Indonesian (Bahasa Indonesia)", "German", "Japanese", "Swahili",
        "Marathi", "Telugu", "Turkish", "Tamil", "Vietnamese", "Korean"
    ];

    const translations = {
        "English": {
            displayLanguage: "Display Language",
            dashboard: "Dashboard",
            chat: "Chat",
            myAgents: "My Agents",
            marketplace: "Marketplace",
            vendorDashboard: "Vendor Dashboard",
            billing: "Billing",
            adminDashboard: "Admin Dashboard",
            updates: "Updates",
            helpFaq: "Help & FAQ",
            logOut: "Log Out",
            joined: "Joined December 2025",
            securityBtn: "Security & Guidelines",
            totalSessions: "Total Sessions",
            proFeatures: "Pro Features",
            accountSettings: "Account Settings",
            credits: "Credits",
            accountPreferences: "Account Preferences",
            timezone: "Timezone",
            currency: "Currency",
            theme: "Theme",
            securityStatus: "Security Status",
            accountSecure: "Account fully secure",
            twoFactor: "Two-Factor Authentication",
            enabled: "Enabled",
            manage: "Manage",
            signOut: "Sign Out from Device"
        },
        "Mandarin Chinese": {
            displayLanguage: "显示语言",
            dashboard: "仪表板",
            chat: "聊天",
            myAgents: "我的代理",
            marketplace: "市场",
            vendorDashboard: "供应商仪表板",
            billing: "计费",
            adminDashboard: "管理仪表板",
            updates: "更新",
            helpFaq: "帮助与常见问题",
            logOut: "登出",
            joined: "2025年12月加入",
            securityBtn: "安全与准则",
            totalSessions: "总会话数",
            proFeatures: "专业功能",
            accountSettings: "账户设置",
            credits: "积分",
            accountPreferences: "账户偏好",
            timezone: "时区",
            currency: "货币",
            theme: "主题",
            securityStatus: "安全状态",
            accountSecure: "账户完全安全",
            twoFactor: "双重认证",
            enabled: "已启用",
            manage: "管理",
            signOut: "退出登录"
        },
        "Hindi": {
            displayLanguage: "प्रदर्शित भाषा",
            dashboard: "डैशबोर्ड",
            chat: "चैट",
            myAgents: "मेरे एजेंट्स",
            marketplace: "बाज़ार",
            vendorDashboard: "विक्रेता डैशबोर्ड",
            billing: "बिलिंग",
            adminDashboard: "एडमिन डैशबोर्ड",
            updates: "अपडेट्स",
            helpFaq: "सहायता और प्रश्न",
            logOut: "लॉग आउट",
            joined: "दिसंबर 2025 में शामिल हुए",
            securityBtn: "सुरक्षा और दिशानिर्देश",
            totalSessions: "कुल सत्र",
            proFeatures: "प्रो सुविधाएँ",
            accountSettings: "खाता सेटिंग्स",
            credits: "क्रेडिट",
            accountPreferences: "खाता वरीयताएँ",
            timezone: "समय क्षेत्र",
            currency: "मुद्रा",
            theme: "थीम",
            securityStatus: "सुरक्षा स्थिति",
            accountSecure: "खाता पूरी तरह सुरक्षित",
            twoFactor: "दो-चरण प्रमाणीकरण",
            enabled: "सक्रिय",
            manage: "प्रबंधित करें",
            signOut: "डिवाइस से साइन आउट करें"
        },
        "Spanish": {
            displayLanguage: "Idioma de Pantalla",
            dashboard: "Tablero",
            chat: "Chat",
            myAgents: "Mis Agentes",
            marketplace: "Mercado",
            vendorDashboard: "Panel de Vendedor",
            billing: "Facturación",
            adminDashboard: "Panel de Administrador",
            updates: "Actualizaciones",
            helpFaq: "Ayuda y Preguntas",
            logOut: "Cerrar Sesión",
            joined: "Se unió en diciembre 2025",
            securityBtn: "Seguridad y Directrices",
            totalSessions: "Sesiones Totales",
            proFeatures: "Funciones Pro",
            accountSettings: "Configuración de Cuenta",
            credits: "Créditos",
            accountPreferences: "Preferencias de Cuenta",
            timezone: "Zona Horaria",
            currency: "Moneda",
            theme: "Tema",
            securityStatus: "Estado de Seguridad",
            accountSecure: "Cuenta totalmente segura",
            twoFactor: "Autenticación de Dos Factores",
            enabled: "Habilitado",
            manage: "Gestionar",
            signOut: "Cerrar Sesión"
        },
        "French": {
            displayLanguage: "Langue d'Affichage",
            dashboard: "Tableau de Bord",
            chat: "Discuter",
            myAgents: "Mes Agents",
            marketplace: "Marché",
            vendorDashboard: "Tableau de Bord Vendeur",
            billing: "Facturation",
            adminDashboard: "Tableau de Bord Admin",
            updates: "Mises à jour",
            helpFaq: "Aide & FAQ",
            logOut: "Se Déconnecter",
            joined: "Rejoint en décembre 2025",
            securityBtn: "Sécurité et Directives",
            totalSessions: "Total des Sessions",
            proFeatures: "Fonctionnalités Pro",
            accountSettings: "Paramètres du Compte",
            credits: "Crédits",
            accountPreferences: "Préférences du Compte",
            timezone: "Fuseau Horaire",
            currency: "Devise",
            theme: "Thème",
            securityStatus: "État de Sécurité",
            accountSecure: "Compte entièrement sécurisé",
            twoFactor: "Authentification à Deux Facteurs",
            enabled: "Activé",
            manage: "Gérer",
            signOut: "Se Déconnecter"
        },
        "Arabic": {
            displayLanguage: "لغة العرض",
            dashboard: "لوحة القيادة",
            chat: "دردشة",
            myAgents: "وكلائي",
            marketplace: "السوق",
            vendorDashboard: "لوحة تحكم البائع",
            billing: "الفواتير",
            adminDashboard: "لوحة مسؤولي النظام",
            updates: "تحديثات",
            helpFaq: "مساعدة وأسئلة",
            logOut: "تسجيل الخروج",
            joined: "انضم في ديسمبر 2025",
            securityBtn: "الأمان والإرشادات",
            totalSessions: "إجمالي الجلسات",
            proFeatures: "ميزات احترافية",
            accountSettings: "إعدادات الحساب",
            credits: "أرصدة",
            accountPreferences: "تفضيلات الحساب",
            timezone: "المنطقة الزمنية",
            currency: "العملة",
            theme: "السمة",
            securityStatus: "حالة الأمان",
            accountSecure: "الحساب آمن بالكامل",
            twoFactor: "المصادقة الثنائية",
            enabled: "مفعّل",
            manage: "إدارة",
            signOut: "تسجيل الخروج"
        },
        "Bengali": {
            displayLanguage: "প্রদর্শনের ভাষা",
            dashboard: "ড্যাশবোর্ড",
            chat: "চ্যাট",
            myAgents: "আমার এজেন্ট",
            marketplace: "মার্কেটপ্লেস",
            vendorDashboard: "ভেন্ডর ড্যাশবোর্ড",
            billing: "বিলিং",
            adminDashboard: "অ্যাডমিন ড্যাশবোর্ড",
            updates: "আপডেট",
            helpFaq: "সাহায্য ও প্রশ্ন",
            logOut: "লগ আউট",
            joined: "ডিসেম্বর ২০২৫ এ যোগ দিয়েছেন",
            securityBtn: "নিরাপত্তা ও নির্দেশিকা",
            totalSessions: "মোট সেশন",
            proFeatures: "প্রো ফিচারস",
            accountSettings: "অ্যাকাউন্ট সেটিংস",
            credits: "ক্রেডিট",
            accountPreferences: "অ্যাকাউন্ট পছন্দসমূহ",
            timezone: "সময় অঞ্চল",
            currency: "মুদ্রা",
            theme: "থিম",
            securityStatus: "নিরাপত্তা স্থিতি",
            accountSecure: "অ্যাকাউন্ট সম্পূর্ণ সুরক্ষিত",
            twoFactor: "দ্বি-স্তর বিশিষ্ট প্রমাণীকরণের",
            enabled: "সক্রিয়",
            manage: "পরিচালনা",
            signOut: "লগ আউট"
        },
        "Portuguese": {
            displayLanguage: "Idioma de Exibição",
            dashboard: "Painel",
            chat: "Chat",
            myAgents: "Meus Agentes",
            marketplace: "Mercado",
            vendorDashboard: "Painel do Vendedor",
            billing: "Faturamento",
            adminDashboard: "Painel de Admin",
            updates: "Atualizações",
            helpFaq: "Ajuda e FAQ",
            logOut: "Sair",
            joined: "Entrou em dezembro de 2025",
            securityBtn: "Segurança e Diretrizes",
            totalSessions: "Sessões Totais",
            proFeatures: "Recursos Pro",
            accountSettings: "Configurações da Conta",
            credits: "Créditos",
            accountPreferences: "Preferências da Conta",
            timezone: "Fuso Horário",
            currency: "Moeda",
            theme: "Tema",
            securityStatus: "Status de Segurança",
            accountSecure: "Conta totalmente segura",
            twoFactor: "Autenticação de Dois Fatores",
            enabled: "Ativado",
            manage: "Gerenciar",
            signOut: "Sair"
        },
        "Russian": {
            displayLanguage: "Язык интерфейса",
            dashboard: "Дашборд",
            chat: "Чат",
            myAgents: "Мои агенты",
            marketplace: "Маркетплейс",
            vendorDashboard: "Панель продавца",
            billing: "Биллинг",
            adminDashboard: "Админ-панель",
            updates: "Обновления",
            helpFaq: "Помощь и FAQ",
            logOut: "Выйти",
            joined: "Присоединился в декабре 2025",
            securityBtn: "Безопасность и правила",
            totalSessions: "Всего сессий",
            proFeatures: "Pro функции",
            accountSettings: "Настройки аккаунта",
            credits: "Кредиты",
            accountPreferences: "Настройки аккаунта",
            timezone: "Часовой пояс",
            currency: "Валюта",
            theme: "Тема",
            securityStatus: "Статус безопасности",
            accountSecure: "Аккаунт полностью защищен",
            twoFactor: "Двухфакторная аутентификация",
            enabled: "Включено",
            manage: "Управлять",
            signOut: "Выйти"
        },
        "Urdu": {
            displayLanguage: "ظاہری زبان",
            dashboard: "ڑیش بورڈ",
            chat: "چیٹ",
            myAgents: "میرے ایجنٹس",
            marketplace: "مارکیٹ پلیس",
            vendorDashboard: "وینڈر ڈیش بورڈ",
            billing: "بلنگ",
            adminDashboard: "ایڈمن ڈیش بورڈ",
            updates: "اپ ڈیٹس",
            helpFaq: "مدد اور سوالات",
            logOut: "لاگ آوٹ",
            joined: "دسمبر 2025 میں شامل ہوئے",
            securityBtn: "سیکیورٹی اور رہنما خطوط",
            totalSessions: "کل سیشنز",
            proFeatures: "پرو خصوصیات",
            accountSettings: "اکاؤنٹ کی ترتیبات",
            credits: "کریڈٹ",
            accountPreferences: "اکاؤنٹ کی ترجیحات",
            timezone: "ٹائم زون",
            currency: "کرنسی",
            theme: "تھیم",
            securityStatus: "سیکیورٹی کی حیثیت",
            accountSecure: "اکاؤنٹ مکمل طور پر محفوظ ہے۔",
            twoFactor: "دو عنصر کی توثیق",
            enabled: "فعال",
            manage: "انتظام کریں",
            signOut: "سائن آؤٹ"
        },
        "Indonesian (Bahasa Indonesia)": {
            displayLanguage: "Bahasa Tampilan",
            dashboard: "Dasbor",
            chat: "Obrolan",
            myAgents: "Agen Saya",
            marketplace: "Pasar",
            vendorDashboard: "Dasbor Vendor",
            billing: "Tagihan",
            adminDashboard: "Dasbor Admin",
            updates: "Pembaruan",
            helpFaq: "Bantuan & FAQ",
            logOut: "Keluar",
            joined: "Bergabung Desember 2025",
            securityBtn: "Keamanan & Pedoman",
            totalSessions: "Total Sesi",
            proFeatures: "Fitur Pro",
            accountSettings: "Pengaturan Akun",
            credits: "Kredit",
            accountPreferences: "Preferensi Akun",
            timezone: "Zona Waktu",
            currency: "Mata Uang",
            theme: "Tema",
            securityStatus: "Status Keamanan",
            accountSecure: "Akun sepenuhnya aman",
            twoFactor: "Otentikasi Dua Faktor",
            enabled: "Diaktifkan",
            manage: "Kelola",
            signOut: "Keluar"
        },
        "German": {
            displayLanguage: "Anzeigesprache",
            dashboard: "Dashboard",
            chat: "Chat",
            myAgents: "Meine Agenten",
            marketplace: "Marktplatz",
            vendorDashboard: "Verkäufer-Dashboard",
            billing: "Abrechnung",
            adminDashboard: "Admin-Dashboard",
            updates: "Aktualisierungen",
            helpFaq: "Hilfe & FAQ",
            logOut: "Abmelden",
            joined: "Beigetreten Dezember 2025",
            securityBtn: "Sicherheit & Richtlinien",
            totalSessions: "Gesamtsitzungen",
            proFeatures: "Pro-Funktionen",
            accountSettings: "Kontoeinstellungen",
            credits: "Guthaben",
            accountPreferences: "Kontoeinstellungen",
            timezone: "Zeitzone",
            currency: "Währung",
            theme: "Thema",
            securityStatus: "Sicherheitsstatus",
            accountSecure: "Konto vollständig sicher",
            twoFactor: "Zwei-Faktor-Authentifizierung",
            enabled: "Aktiviert",
            manage: "Verwalten",
            signOut: "Abmelden"
        },
        "Japanese": {
            displayLanguage: "表示言語",
            dashboard: "ダッシュボード",
            chat: "チャット",
            myAgents: "マイエージェント",
            marketplace: "マーケットプレイス",
            vendorDashboard: "ベンダーダッシュボード",
            billing: "請求",
            adminDashboard: "管理ダッシュボード",
            updates: "更新",
            helpFaq: "ヘルプとFAQ",
            logOut: "ログアウト",
            joined: "2025年12月に参加",
            securityBtn: "セキュリティとガイドライン",
            totalSessions: "総セッション数",
            proFeatures: "プロ機能",
            accountSettings: "アカウント設定",
            credits: "クレジット",
            accountPreferences: "アカウント設定",
            timezone: "タイムゾーン",
            currency: "通貨",
            theme: "テーマ",
            securityStatus: "セキュリティステータス",
            accountSecure: "アカウントは完全に安全です",
            twoFactor: "二要素認証",
            enabled: "有効",
            manage: "管理",
            signOut: "サインアウト"
        },
        "Swahili": {
            displayLanguage: "Lugha ya Onyesho",
            dashboard: "Dashibodi",
            chat: "Gumzo",
            myAgents: "Mawakala Wangu",
            marketplace: "Soko",
            vendorDashboard: "Dashibodi ya Muuzaji",
            billing: "Malipo",
            adminDashboard: "Dashibodi ya Msimamizi",
            updates: "Sasisho",
            helpFaq: "Msaada na Maswali",
            logOut: "Ondoka",
            joined: "Alijiunga Desemba 2025",
            securityBtn: "Usalama na Miongozo",
            totalSessions: "Viko vya Jumla",
            proFeatures: "Vipengele vya Pro",
            accountSettings: "Mipangilio ya Akaunti",
            credits: "Mikopo",
            accountPreferences: "Mapendeleo ya Akaunti",
            timezone: "Ukanda wa saa",
            currency: "Sarafu",
            theme: "Mandhari",
            securityStatus: "Hali ya Usalama",
            accountSecure: "Akaunti imelindwa kikamilifu",
            twoFactor: "Uthibitishaji wa Hatua Mbili",
            enabled: "Imewezeshwa",
            manage: "Dhibiti",
            signOut: "Ondoka"
        },
        "Marathi": {
            displayLanguage: "प्रदर्शन भाषा",
            dashboard: "डॅशबोर्ड",
            chat: "चॅट",
            myAgents: "माझे एजंट्स",
            marketplace: "बाजारपेठ",
            vendorDashboard: "विक्रेता डॅशबोर्ड",
            billing: "बिलिंग",
            adminDashboard: "अ‍ॅडमिन डॅशबोर्ड",
            updates: "अपडेट्स",
            helpFaq: "मदत आणि प्रश्न",
            logOut: "लॉग आउट",
            joined: "डिसेंबर 2025 मध्ये सामील झाले",
            securityBtn: "सुरक्षा आणि मार्गदर्शक तत्त्वे",
            totalSessions: "एकूण सत्रे",
            proFeatures: "प्रो वैशिष्ट्ये",
            accountSettings: "खाते सेटिंग्ज",
            credits: "क्रेडिट्स",
            accountPreferences: "खाते प्राधान्ये",
            timezone: "वेळ क्षेत्र",
            currency: "चलन",
            theme: "थीम",
            securityStatus: "सुरक्षा स्थिती",
            accountSecure: "खातेपूर्णपणे सुरक्षित",
            twoFactor: "दोन-चरण प्रमाणीकरण",
            enabled: "सक्षम",
            manage: "व्यवस्थापित करा",
            signOut: "बाहेर पडा"
        },
        "Telugu": {
            displayLanguage: "ప్రదర్శన భాష",
            dashboard: "డాష్‌బోర్డ్",
            chat: "చాట్",
            myAgents: "నా ఏజెంట్లు",
            marketplace: "మార్కెట్‌ప్లేస్",
            vendorDashboard: "విక్రేత డాష్‌బోర్డ్",
            billing: "బిల్లింగ్",
            adminDashboard: "అడ్మిన్ డాష్‌బోర్డ్",
            updates: "నవీకరణలు",
            helpFaq: "సహాయం & ప్రశ్నలు",
            logOut: "లాగ్ అవుట్",
            joined: "డిసెంబర్ 2025లో చేరారు",
            securityBtn: "భద్రత & మార్గదర్శకాలు",
            totalSessions: "మొత్తం సెషన్లు",
            proFeatures: "ప్రో ఫీచర్లు",
            accountSettings: "ఖాతా సెట్టింగ్‌లు",
            credits: "క్రెడిట్స్",
            accountPreferences: "ఖాతా ప్రాధాన్యతలు",
            timezone: "సమయ క్షేత్రం",
            currency: "కరెన్సీ",
            theme: "థీమ్",
            securityStatus: "భద్రతా స్థితి",
            accountSecure: "ఖాతా పూర్తిగా సురక్షితం",
            twoFactor: "రెండు-కారకాల ప్రమాణీకరణ",
            enabled: "ప్రారంభించబడింది",
            manage: "నిర్వహించండి",
            signOut: "సైన్ అవుట్ చేయండి"
        },
        "Turkish": {
            displayLanguage: "Görüntüleme Dili",
            dashboard: "Kontrol Paneli",
            chat: "Sohbet",
            myAgents: "Ajanlarım",
            marketplace: "Pazar Yeri",
            vendorDashboard: "Satıcı Paneli",
            billing: "Faturalandırma",
            adminDashboard: "Yönetici Paneli",
            updates: "Güncellemeler",
            helpFaq: "Yardım ve SSS",
            logOut: "Çıkış Yap",
            joined: "Aralık 2025'te katıldı",
            securityBtn: "Güvenlik ve Yönergeler",
            totalSessions: "Toplam Oturumlar",
            proFeatures: "Pro Özellikler",
            accountSettings: "Hesap Ayarları",
            credits: "Krediler",
            accountPreferences: "Hesap Tercihleri",
            timezone: "Saat Dilimi",
            currency: "Para Birimi",
            theme: "Tema",
            securityStatus: "Güvenlik Durumu",
            accountSecure: "Hesap tamamen güvenli",
            twoFactor: "İki Faktörlü Kimlik Doğrulama",
            enabled: "Etkin",
            manage: "Yönet",
            signOut: "Çıkış Yap"
        },
        "Tamil": {
            displayLanguage: "காட்சி மொழி",
            dashboard: "முகப்பு",
            chat: "அரட்டை",
            myAgents: "என் முகவர்கள்",
            marketplace: "சந்தை",
            vendorDashboard: "விற்பனையாளர் முகப்பு",
            billing: "பில்லிங்",
            adminDashboard: "நிர்வாக முகப்பு",
            updates: "புதுப்பிப்புகள்",
            helpFaq: "உதவி & கேள்விகள்",
            logOut: "வெளியேறு",
            joined: "டிசம்பர் 2025 இல் இணைந்தார்",
            securityBtn: "பாதுகாப்பு & வழிகாட்டுதல்கள்",
            totalSessions: "மொத்த அமர்வுகள்",
            proFeatures: "ப்ரோ அம்சங்கள்",
            accountSettings: "கணக்கு அமைப்புகள்",
            credits: "க्रेडिटஸ்",
            accountPreferences: "கணக்கு விருப்பங்கள்",
            timezone: "நேர மண்டலம்",
            currency: "நாணயம்",
            theme: "தீம்",
            securityStatus: "பாதுகாப்பு நிலை",
            accountSecure: "கணக்கு முழுமையாக பாதுகாப்பானது",
            twoFactor: "இரண்டு காரணி அங்கீகாரம்",
            enabled: "இயக்கப்பட்டது",
            manage: "நிர்வகி",
            signOut: "வெளியேறு"
        },
        "Vietnamese": {
            displayLanguage: "Ngôn ngữ hiển thị",
            dashboard: "Bảng điều khiển",
            chat: "Trò chuyện",
            myAgents: "Đại lý của tôi",
            marketplace: "Chợ",
            vendorDashboard: "Bảng điều khiển nhà cung cấp",
            billing: "Thanh toán",
            adminDashboard: "Bảng quản trị",
            updates: "Cập nhật",
            helpFaq: "Trợ giúp & FAQ",
            logOut: "Đăng xuất",
            joined: "Đã tham gia tháng 12 năm 2025",
            securityBtn: "Bảo mật & Hướng dẫn",
            totalSessions: "Tổng số phiên",
            proFeatures: "Tính năng Pro",
            accountSettings: "Cài đặt tài khoản",
            credits: "Tín dụng",
            accountPreferences: "Tùy chọn tài khoản",
            timezone: "Múi giờ",
            currency: "Tiền tệ",
            theme: "Chủ đề",
            securityStatus: "Trạng thái bảo mật",
            accountSecure: "Tài khoản an toàn tuyệt đối",
            twoFactor: "Xác thực hai yếu tố",
            enabled: "Đã bật",
            manage: "Quản lý",
            signOut: "Đăng xuất"
        },
        "Korean": {
            displayLanguage: "표시 언어",
            dashboard: "대시보드",
            chat: "채팅",
            myAgents: "내 에이전트",
            marketplace: "마켓플레이스",
            vendorDashboard: "벤더 대시보드",
            billing: "청구",
            adminDashboard: "관리자 대시보드",
            updates: "업데이트",
            helpFaq: "도움말 및 FAQ",
            logOut: "로그아웃",
            joined: "2025년 12월 가입",
            securityBtn: "보안 및 지침",
            totalSessions: "총 세션",
            proFeatures: "프로 기능",
            accountSettings: "계정 설정",
            credits: "크레딧",
            accountPreferences: "계정 기본 설정",
            timezone: "시간대",
            currency: "통화",
            theme: "테마",
            securityStatus: "보안 상태",
            accountSecure: "계정이 완전히 안전합니다",
            twoFactor: "2단계 인증",
            enabled: "활성화됨",
            manage: "관리",
            signOut: "로그아웃"
        }
    };

    // Fallback for missing languages in this snippet, the real file will have all.
    // I will use a helper to ensure safety.
    const t = (key) => {
        const langData = translations[language] || translations['English'];
        return langData[key] || translations['English'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, languages }}>
            {children}
        </LanguageContext.Provider>
    );
};
