import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [region, setRegion] = useState(localStorage.getItem('user-region') || 'India');
    const [language, setLanguage] = useState(localStorage.getItem('user-language') || 'English');

    useEffect(() => {
        localStorage.setItem('user-region', region);
    }, [region]);

    useEffect(() => {
        localStorage.setItem('user-language', language);
    }, [language]);

    const regions = {
        'India': ["English", "Hindi", "Bengali", "Marathi", "Telugu", "Tamil", "Kannada", "Malayalam", "Urdu"],
        'United States': ["English", "Spanish", "French", "Mandarin Chinese"],
        'Japan': ["Japanese", "English"],
        'China': ["Mandarin Chinese", "English"],
        'Germany': ["German", "English"],
        'France': ["French", "English"],
        'Brazil': ["Portuguese", "English"],
        'United Kingdom': ["English"],
        'United Arab Emirates': ["Arabic", "English"],
        'Canada': ["English", "French"],
        'Spain': ["Spanish", "English"],
        'South Korea': ["Korean", "English"],
        'Italy': ["Italian", "English"],
        'Russia': ["Russian", "English"],
        'Australia': ["English"],
        'Singapore': ["English", "Mandarin Chinese", "Malayalam", "Tamil"],
        'Netherlands': ["Dutch", "English"],
        'Mexico': ["Spanish", "English"],
        'Turkey': ["Turkish", "English"],
        'Switzerland': ["German", "French", "Italian", "English"],
        'Sweden': ["Swedish", "English"],
        'Norway': ["Norwegian", "English"],
        'Denmark': ["Danish", "English"],
        'Finland': ["Finnish", "English"],
        'Belgium': ["Dutch", "French", "German", "English"],
        'Argentina': ["Spanish", "English"],
        'Portugal': ["Portuguese", "English"],
        'New Zealand': ["English"],
        'South Africa': ["English", "Afrikaans", "Zulu", "Xhosa"]
    };

    const regionFlags = {
        'India': 'IN',
        'United States': 'US',
        'Japan': 'JP',
        'China': 'CN',
        'Germany': 'DE',
        'France': 'FR',
        'Brazil': 'BR',
        'United Kingdom': 'GB',
        'United Arab Emirates': 'AE',
        'Canada': 'CA',
        'Spain': 'ES',
        'South Korea': 'KR',
        'Italy': 'IT',
        'Russia': 'RU',
        'Australia': 'AU',
        'Singapore': 'SG',
        'Netherlands': 'NL',
        'Mexico': 'MX',
        'Turkey': 'TR',
        'Switzerland': 'CH',
        'Sweden': 'SE',
        'Norway': 'NO',
        'Denmark': 'DK',
        'Finland': 'FI',
        'Belgium': 'BE',
        'Argentina': 'AR',
        'Portugal': 'PT',
        'New Zealand': 'NZ',
        'South Africa': 'ZA'
    };

    const regionTimezones = {
        'India': 'India (GMT+5:30)',
        'United States': 'Eastern Time (GMT-5:00)',
        'Japan': 'Japan Standard Time (GMT+9:00)',
        'China': 'China Standard Time (GMT+8:00)',
        'Germany': 'Central European Time (GMT+1:00)',
        'France': 'Central European Time (GMT+1:00)',
        'Brazil': 'Brasília Time (GMT-3:00)',
        'United Kingdom': 'Greenwich Mean Time (GMT+0:00)',
        'United Arab Emirates': 'Gulf Standard Time (GMT+4:00)',
        'Canada': 'Eastern Time (GMT-5:00)',
        'Spain': 'Central European Time (GMT+1:00)',
        'South Korea': 'Korea Standard Time (GMT+9:00)',
        'Italy': 'Central European Time (GMT+1:00)',
        'Russia': 'Moscow Time (GMT+3:00)',
        'Australia': 'Australian Eastern Time (GMT+10:00)',
        'Singapore': 'Singapore Time (GMT+8:00)',
        'Netherlands': 'Central European Time (GMT+1:00)',
        'Mexico': 'Central Standard Time (GMT-6:00)',
        'Turkey': 'Turkey Time (GMT+3:00)',
        'Switzerland': 'Central European Time (GMT+1:00)',
        'Sweden': 'Central European Time (GMT+1:00)',
        'Norway': 'Central European Time (GMT+1:00)',
        'Denmark': 'Central European Time (GMT+1:00)',
        'Finland': 'Eastern European Time (GMT+2:00)',
        'Belgium': 'Central European Time (GMT+1:00)',
        'Argentina': 'Argentina Time (GMT-3:00)',
        'Portugal': 'Western European Time (GMT+0:00)',
        'New Zealand': 'New Zealand Time (GMT+12:00)',
        'South Africa': 'South Africa Time (GMT+2:00)'
    };

    const allTimezones = [
        "International Date Line West (GMT-12:00)",
        "Samoa Standard Time (GMT-11:00)",
        "Hawaii-Aleutian Standard Time (GMT-10:00)",
        "Alaska Standard Time (GMT-9:00)",
        "Pacific Standard Time (GMT-8:00)",
        "Mountain Standard Time (GMT-7:00)",
        "Central Standard Time (GMT-6:00)",
        "Eastern Standard Time (GMT-5:00)",
        "Atlantic Standard Time (GMT-4:00)",
        "Brasília Time (GMT-3:00)",
        "South Georgia Time (GMT-2:00)",
        "Azores Time (GMT-1:00)",
        "Greenwich Mean Time (GMT+0:00)",
        "Central European Time (GMT+1:00)",
        "Eastern European Time (GMT+2:00)",
        "Moscow Time (GMT+3:00)",
        "Gulf Standard Time (GMT+4:00)",
        "India Standard Time (GMT+5:30)",
        "Bangladesh Standard Time (GMT+6:00)",
        "Indochina Time (GMT+7:00)",
        "China Standard Time (GMT+8:00)",
        "Japan Standard Time (GMT+9:00)",
        "Australian Eastern Time (GMT+10:00)",
        "Solomon Islands Time (GMT+11:00)",
        "New Zealand Time (GMT+12:00)"
    ];

    const languages = [].concat(...Object.values(regions));
    const uniqueLanguages = [...new Set(languages)];

    const translations = {
        "English": {
            displayLanguage: "Display Language",
            dashboard: "Dashboard",
            chat: "Chat",
            myAgents: "My Agents",
            marketplace: "Marketplace",
            vendorDashboard: "Vendor Dashboard",
            billing: "Billing",
            adminDashboard: "Admin Dashboard",
            updates: "Updates",
            helpFaq: "Help & FAQ",
            logOut: "Log Out",
            joined: "Joined December 2025",
            securityBtn: "Security & Guidelines",
            totalSessions: "Total Sessions",
            proFeatures: "Pro Features",
            accountSettings: "Account Settings",
            credits: "Credits",
            accountPreferences: "Account Preferences",
            timezone: "Timezone",
            currency: "Currency",
            theme: "Theme",
            securityStatus: "Security Status",
            accountSecure: "Account fully secure",
            twoFactor: "Two-Factor Authentication",
            enabled: "Enabled",
            manage: "Manage",
            signOut: "Sign Out from Device"
        },
        "Hindi": {
            displayLanguage: "प्रदर्शित भाषा",
            dashboard: "डैशबोर्ड",
            chat: "चैट",
            myAgents: "मेरे एजेंट",
            marketplace: "मार्केटप्लेस",
            vendorDashboard: "विक्रेता डैशबोर्ड",
            billing: "बिलिंग",
            adminDashboard: "व्यवस्थापक डैशबोर्ड",
            updates: "अपडेट",
            helpFaq: "सहायता और FAQ",
            logOut: "लॉग आउट",
            joined: "दिसंबर 2025 को शामिल हुए",
            securityBtn: "सुरक्षा और दिशानिर्देश",
            totalSessions: "कुल सत्र",
            proFeatures: "प्रो सुविधाएँ",
            accountSettings: "खाता सेटिंग्स",
            credits: "क्रेडिट",
            accountPreferences: "खाता प्राथमिकताएं",
            timezone: "समय क्षेत्र",
            currency: "मुद्रा",
            theme: "थीम",
            securityStatus: "सुरक्षा स्थिति",
            accountSecure: "खाता पूरी तरह से सुरक्षित है",
            twoFactor: "दो-चरणीय प्रमाणीकरण",
            enabled: "सक्षम",
            manage: "प्रबंधित करें",
            signOut: "साइन आउट करें"
        },
        "Spanish": {
            displayLanguage: "Idioma de pantalla",
            dashboard: "Tablero",
            chat: "Chat",
            myAgents: "Mis agentes",
            marketplace: "Mercado",
            vendorDashboard: "Tablero del vendedor",
            billing: "Facturación",
            adminDashboard: "Tablero del administrador",
            updates: "Actualizaciones",
            helpFaq: "Ayuda y FAQ",
            logOut: "Cerrar sesión",
            joined: "Se unió en diciembre de 2025",
            securityBtn: "Seguridad y directrices",
            totalSessions: "Sesiones totales",
            proFeatures: "Funciones Pro",
            accountSettings: "Configuración de la cuenta",
            credits: "Créditos",
            accountPreferences: "Preferencias de la cuenta",
            timezone: "Zona horaria",
            currency: "Moneda",
            theme: "Tema",
            securityStatus: "Estado de seguridad",
            accountSecure: "Cuenta totalmente segura",
            twoFactor: "Autenticación de dos factores",
            enabled: "Habilitado",
            manage: "Administrar",
            signOut: "Cerrar sesión"
        },
        "French": {
            displayLanguage: "Langue d'affichage",
            dashboard: "Tableau de bord",
            chat: "Chat",
            myAgents: "Mes agents",
            marketplace: "Marché",
            vendorDashboard: "Tableau de bord vendeur",
            billing: "Facturation",
            adminDashboard: "Tableau de bord administrateur",
            updates: "Mises à jour",
            helpFaq: "Aide & FAQ",
            logOut: "Déconnexion",
            joined: "Inscrit en décembre 2025",
            securityBtn: "Sécurité & Directives",
            totalSessions: "Total des sessions",
            proFeatures: "Fonctions Pro",
            accountSettings: "Paramètres du compte",
            credits: "Crédits",
            accountPreferences: "Préférences du compte",
            timezone: "Fuseau horaire",
            currency: "Devise",
            theme: "Thème",
            securityStatus: "État de sécurité",
            accountSecure: "Compte entièrement sécurisé",
            twoFactor: "Authentification à deux facteurs",
            enabled: "Activé",
            manage: "Gérer",
            signOut: "Déconnexion"
        },
        "Japanese": {
            displayLanguage: "表示言語",
            dashboard: "ダッシュボード",
            chat: "チャット",
            myAgents: "マイエージェント",
            marketplace: "マーケットプレイス",
            vendorDashboard: "ベンダーダッシュボード",
            billing: "請求",
            adminDashboard: "管理ダッシュボード",
            updates: "アップデート",
            helpFaq: "ヘルプとFAQ",
            logOut: "ログアウト",
            joined: "2025年12月に参加",
            securityBtn: "セキュリティとガイドライン",
            totalSessions: "合計セッション数",
            proFeatures: "プロ機能",
            accountSettings: "アカウント設定",
            credits: "クレジット",
            accountPreferences: "アカウント設定",
            timezone: "タイムゾーン",
            currency: "通貨",
            theme: "テーマ",
            securityStatus: "セキュリティステータス",
            accountSecure: "アカウントは完全に安全です",
            twoFactor: "2段階認証",
            enabled: "有効",
            manage: "管理",
            signOut: "サインアウト"
        },
        "German": {
            displayLanguage: "Anzeigesprache",
            dashboard: "Dashboard",
            chat: "Chat",
            myAgents: "Meine Agenten",
            marketplace: "Marktplatz",
            vendorDashboard: "Verkäufer-Dashboard",
            billing: "Abrechnung",
            adminDashboard: "Admin-Dashboard",
            updates: "Updates",
            helpFaq: "Hilfe & FAQ",
            logOut: "Abmelden",
            joined: "Beigetreten im Dezember 2025",
            securityBtn: "Sicherheit & Richtlinien",
            totalSessions: "Gesamte Sitzungen",
            proFeatures: "Pro-Funktionen",
            accountSettings: "Kontoeinstellungen",
            credits: "Credits",
            accountPreferences: "Kontoeinstellungen",
            timezone: "Zeitzone",
            currency: "Währung",
            theme: "Thema",
            securityStatus: "Sicherheitsstatus",
            accountSecure: "Konto vollständig sicher",
            twoFactor: "Zwei-Faktor-Authentifizierung",
            enabled: "Aktiviert",
            manage: "Verwalten",
            signOut: "Abmelden"
        },
        "Portuguese": {
            displayLanguage: "Idioma de exibição",
            dashboard: "Painel",
            chat: "Chat",
            myAgents: "Meus Agentes",
            marketplace: "Marketplace",
            vendorDashboard: "Painel do Vendedor",
            billing: "Faturamento",
            adminDashboard: "Painel do Administrador",
            updates: "Atualizações",
            helpFaq: "Ajuda e FAQ",
            logOut: "Sair",
            joined: "Entrou em dezembro de 2025",
            securityBtn: "Segurança e Diretrizes",
            totalSessions: "Total de sessões",
            proFeatures: "Recursos Pro",
            accountSettings: "Configurações da conta",
            credits: "Créditos",
            accountPreferences: "Preferências da conta",
            timezone: "Fuso horário",
            currency: "Moeda",
            theme: "Tema",
            securityStatus: "Estado de segurança",
            accountSecure: "Conta totalmente segura",
            twoFactor: "Autenticação de dois fatores",
            enabled: "Ativado",
            manage: "Gerenciar",
            signOut: "Sair"
        },
        "Korean": {
            displayLanguage: "표시 언어",
            dashboard: "대시보드",
            chat: "채팅",
            myAgents: "내 에이전트",
            marketplace: "마켓플레이스",
            vendorDashboard: "판매자 대시보드",
            billing: "결제",
            adminDashboard: "관리자 대시보드",
            updates: "업데이트",
            helpFaq: "도움말 및 FAQ",
            logOut: "로그아웃",
            joined: "2025년 12월 가입",
            securityBtn: "보안 및 지침",
            totalSessions: "총 세션",
            proFeatures: "프로 기능",
            accountSettings: "계정 설정",
            credits: "크레딧",
            accountPreferences: "계정 기본 설정",
            timezone: "시간대",
            currency: "통화",
            theme: "테마",
            securityStatus: "보안 상태",
            accountSecure: "계정이 완전히 안전합니다",
            twoFactor: "2단계 인증",
            enabled: "활성화됨",
            manage: "관리",
            signOut: "로그아웃"
        },
        "Russian": {
            displayLanguage: "Язык интерфейса",
            dashboard: "Панель управления",
            chat: "Чат",
            myAgents: "Мои агенты",
            marketplace: "Маркетплейс",
            vendorDashboard: "Панель поставщика",
            billing: "Биллинг",
            adminDashboard: "Панель администратора",
            updates: "Обновления",
            helpFaq: "Помощь и FAQ",
            logOut: "Выйти",
            joined: "Присоединился в декабре 2025",
            securityBtn: "Безопасность и правила",
            totalSessions: "Всего сессий",
            proFeatures: "Про-функции",
            accountSettings: "Настройки аккаунта",
            credits: "Кредиты",
            accountPreferences: "Настройки аккаунта",
            timezone: "Часовой пояс",
            currency: "Валюта",
            theme: "Тема",
            securityStatus: "Статус безопасности",
            accountSecure: "Аккаунт полностью защищен",
            twoFactor: "Двухфакторная аутентификация",
            enabled: "Включено",
            manage: "Управлять",
            signOut: "Выйти"
        },
        "Arabic": {
            displayLanguage: "لغة العرض",
            dashboard: "لوحة التحكم",
            chat: "دردشة",
            myAgents: "عملائي",
            marketplace: "المتجر",
            vendorDashboard: "لوحة تحكم البائع",
            billing: "الفواتير",
            adminDashboard: "لوحة تحكم المشرف",
            updates: "التحديثات",
            helpFaq: "المساعدة والأسئلة الشائعة",
            logOut: "تسجيل الخروج",
            joined: "انضم في ديسمبر 2025",
            securityBtn: "الأمان والإرشادات",
            totalSessions: "إجمالي الجلسات",
            proFeatures: "ميزات برو",
            accountSettings: "إعدادات الحساب",
            credits: "رصيد",
            accountPreferences: "تفضيلات الحساب",
            timezone: "المنطقة الزمنية",
            currency: "العملة",
            theme: "المظهر",
            securityStatus: "حالة الأمان",
            accountSecure: "الحساب آمن تمامًا",
            twoFactor: "المصادقة الثنائية",
            enabled: "ممكن",
            manage: "إدارة",
            signOut: "تسجيل الخروج"
        },
        "Bengali": {
            displayLanguage: "প্রদর্শন ভাষা",
            dashboard: "ড্যাশবোর্ড",
            chat: "চ্যাট",
            myAgents: "আমার এজেন্ট",
            marketplace: "মার্কেটপ্লেস",
            vendorDashboard: "ভেন্ডর ড্যাশবোর্ড",
            billing: "বিলিং",
            adminDashboard: "অ্যাডমিন ড্যাশবোর্ড",
            updates: "আপডেট",
            helpFaq: "সহায়তা এবং FAQ",
            logOut: "লগ আউট",
            joined: "ডিসেম্বর ২০২৫ এ যোগদান করেছেন",
            securityBtn: "নিরাপত্তা ও নির্দেশিকা",
            totalSessions: "মোট সেশন",
            proFeatures: "প্রো বৈশিষ্ট্য",
            accountSettings: "অ্যাকাউন্ট সেটিংস",
            credits: "ক্রেডিট",
            accountPreferences: "অ্যাকাউন্ট পছন্দসমূহ",
            timezone: "সময় অঞ্চল",
            currency: "মুদ্রা",
            theme: "থিম",
            securityStatus: "নিরাপত্তা অবস্থা",
            accountSecure: "অ্যাকাউন্ট সম্পূর্ণ নিরাপদ",
            twoFactor: "টু-ফ্যাক্টর অথেন্টিকেশন",
            enabled: "সক্রিয়",
            manage: "পরিচালনা করুন",
            signOut: "সাইন আউট করুন"
        },
        "Marathi": {
            displayLanguage: "प्रदर्शित भाषा",
            dashboard: "डॅशबोर्ड",
            chat: "चॅट",
            myAgents: "माझे एजंट",
            marketplace: "मार्केटप्लेस",
            vendorDashboard: "विक्रेता डॅशबोर्ड",
            billing: "बिलिंग",
            adminDashboard: "प्रशासक डॅशबोर्ड",
            updates: "अपडेट्स",
            helpFaq: "मदत आणि FAQ",
            logOut: "लॉग आउट",
            joined: "डिसेंबर २०२५ मध्ये सामील झाले",
            securityBtn: "सुरक्षा आणि मार्गदर्शक तत्वे",
            totalSessions: "एकूण सत्रे",
            proFeatures: "प्रो वैशिष्ट्ये",
            accountSettings: "खाते सेटिंग्ज",
            credits: "क्रेडिट्स",
            accountPreferences: "खाते पसंती",
            timezone: "वेळ क्षेत्र",
            currency: "चलन",
            theme: "थीम",
            securityStatus: "सुरक्षा स्थिती",
            accountSecure: "खाते पूर्णपणे सुरक्षित आहे",
            twoFactor: "द्वि-घटक प्रमाणीकरण",
            enabled: "सक्षम",
            manage: "व्यवस्थापित करा",
            signOut: "साइन आउट करा"
        },
        "Telugu": {
            displayLanguage: "ప్రదర్శన భాష",
            dashboard: "డాష్‌బోర్డ్",
            chat: "చాట్",
            myAgents: "నా ఏజెంట్లు",
            marketplace: "మార్కెట్‌ప్లేస్",
            vendorDashboard: "విక్రేత డాష్‌బోర్డ్",
            billing: "బిల్లింగ్",
            adminDashboard: "అడ్మిన్ డాష్‌బోర్డ్",
            updates: "నవీకరణలు",
            helpFaq: "సహాయం & ప్రశ్నలు",
            logOut: "లాగ్ అవుట్",
            joined: "డిసెంబర్ 2025లో చేరారు",
            securityBtn: "భద్రత & మార్గదర్శకాలు",
            totalSessions: "మొత్తం సెషన్లు",
            proFeatures: "ప్రో ఫీచర్లు",
            accountSettings: "ఖాతా సెట్టింగ్‌లు",
            credits: "క్రెడిట్స్",
            accountPreferences: "ఖాతా ప్రాధాన్యతలు",
            timezone: "సమయ క్షేత్రం",
            currency: "కరెన్సీ",
            theme: "థీమ్",
            securityStatus: "భద్రతా స్థితి",
            accountSecure: "ఖాతా పూర్తిగా సురక్షితం",
            twoFactor: "రెండు-కారకాల ప్రమాణీకరణ",
            enabled: "ప్రారంభించబడింది",
            manage: "నిర్వహించండి",
            signOut: "సైన్ అవుట్ చేయండి"
        },
        "Turkish": {
            displayLanguage: "Görüntüleme Dili",
            dashboard: "Kontrol Paneli",
            chat: "Sohbet",
            myAgents: "Ajanlarım",
            marketplace: "Pazar Yeri",
            vendorDashboard: "Satıcı Paneli",
            billing: "Faturalandırma",
            adminDashboard: "Yönetici Paneli",
            updates: "Güncellemeler",
            helpFaq: "Yardım ve SSS",
            logOut: "Çıkış Yap",
            joined: "Aralık 2025'te katıldı",
            securityBtn: "Güvenlik ve Yönergeler",
            totalSessions: "Toplam Oturumlar",
            proFeatures: "Pro Özellikler",
            accountSettings: "Hesap Ayarları",
            credits: "Krediler",
            accountPreferences: "Hesap Tercihleri",
            timezone: "Saat Dilimi",
            currency: "Para Birimi",
            theme: "Tema",
            securityStatus: "Güvenlik Durumu",
            accountSecure: "Hesap tamamen güvenli",
            twoFactor: "İki Faktörlü Kimlik Doğrulama",
            enabled: "Etkin",
            manage: "Yönet",
            signOut: "Çıkış Yap"
        },
        "Tamil": {
            displayLanguage: "காட்சி மொழி",
            dashboard: "முகப்பு",
            chat: "அரட்டை",
            myAgents: "என் முகவர்கள்",
            marketplace: "சந்தை",
            vendorDashboard: "விற்பனையாளர் முகப்பு",
            billing: "பில்லிங்",
            adminDashboard: "நிர்வாக முகப்பு",
            updates: "புதுப்பிப்புகள்",
            helpFaq: "உதவி & கேள்விகள்",
            logOut: "வெளியேறு",
            joined: "டிசம்பர் 2025 இல் இணைந்தார்",
            securityBtn: "பாதுகாப்பு & வழிகாட்டுதல்கள்",
            totalSessions: "மொத்த அமர்வுகள்",
            proFeatures: "ப்ரோ அம்சங்கள்",
            accountSettings: "கணக்கு அமைப்புகள்",
            credits: "க्रेडिटస్",
            accountPreferences: "கணக்கு விருப்பங்கள்",
            timezone: "நேர மண்டலம்",
            currency: "நாணயம்",
            theme: "தீம்",
            securityStatus: "பாதுகாப்பு நிலை",
            accountSecure: "கணக்கு முழுமையாக பாதுகாப்பானது",
            twoFactor: "இரண்டு காரணி அங்கீகாரம்",
            enabled: "இயக்கப்பட்டது",
            manage: "நிர்வகி",
            signOut: "வெளியேறு"
        },
        "Kannada": {
            displayLanguage: "ಪ್ರದರ್ಶನ ಭಾಷೆ",
            dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
            chat: "ಚಾಟ್",
            myAgents: "ನನ್ನ ಏಜೆಂಟ್‌ಗಳು",
            marketplace: "ಮಾರುಕಟ್ಟೆ",
            vendorDashboard: "ಮಾರಾಟಗಾರರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
            billing: "ಬಿಲ್ಲಿಂಗ್",
            adminDashboard: "ಅಡ್ಮಿನ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
            updates: "ನವೀಕರಣಗಳು",
            helpFaq: "ಸಹಾಯ ಮತ್ತು FAQ",
            logOut: "ಲಾಗ್ ಔಟ್",
            joined: "ಡಿಸೆಂಬರ್ 2025 ರಂದು ಸೇರಿದ್ದಾರೆ",
            securityBtn: "ಭದ್ರತೆ ಮತ್ತು ಮಾರ್ಗಸೂಚಿಗಳು",
            totalSessions: "ಒಟ್ಟು ಸೆಷನ್‌ಗಳು",
            proFeatures: "ಪ್ರೊ ವೈಶಿಷ್ಟ್ಯಗಳು",
            accountSettings: "ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
            credits: "ಕ್ರೆಡಿಟ್ಸ್",
            accountPreferences: "ಖಾತೆ ಆದ್ಯತೆಗಳು",
            timezone: "ಸಮಯ ವಲಯ",
            currency: "ಕರೆನ್ಸಿ",
            theme: "ಥೀಮ್",
            securityStatus: "ಭದ್ರತಾ ಸ್ಥితి",
            accountSecure: "ಖಾತೆ ಸಂಪೂರ್ಣವಾಗಿ ಸುರಕ್ಷಿತವಾಗಿದೆ",
            twoFactor: "ದ್ವಿ-ಅಂಶ ದೃಢೀಕರಣ",
            enabled: "ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ",
            manage: "ನಿರ್ವಹಿಸಿ",
            signOut: "ಸೈನ್ ಔಟ್"
        },
        "Malayalam": {
            displayLanguage: "ಪ್ರದರ್ಶನ ಭಾಷೆ",
            dashboard: "ഡാഷ്‌ബോർഡ്",
            chat: "ചാറ്റ്",
            myAgents: "എന്റെ ഏജന്റുകൾ",
            marketplace: "മാർക്കറ്റ് പ്ലേസ്",
            vendorDashboard: "വെണ്ടർ ഡാഷ്‌ബോർഡ്",
            billing: "ബില്ലിംഗ്",
            adminDashboard: "അഡ്മിൻ ഡാഷ്‌ബോർഡ്",
            updates: "അപ്‌ഡേറ്റുകൾ",
            helpFaq: "സഹായം & FAQ",
            logOut: "ലോഗ് ഔട്ട്",
            joined: "2025 ഡിസംബറിൽ ചേർന്നു",
            securityBtn: "സുരക്ഷയും മാർഗ്ഗനിർദ്ദേശങ്ങളും",
            totalSessions: "ആകെ സെഷനുകൾ",
            proFeatures: "ప్రో ఫీచర్లు",
            accountSettings: "అക്കൗണ്ട് ക്രമീകരണങ്ങൾ",
            credits: "ക്രെഡിറ്റുകൾ",
            accountPreferences: "അക്കൗണ്ട് മുൻഗണനകൾ",
            timezone: "സമയ മേഖല",
            currency: "കറൻസി",
            theme: "തീം",
            securityStatus: "സുരക്ഷാ നില",
            accountSecure: "അക്കൗണ്ട് പൂർണ്ണമായും സുരക്ഷിതമാണ്",
            twoFactor: "ടു-ഫാക്ടർ ഓതന്റിക്കേഷൻ",
            enabled: "പ്രവർത്തനക്ഷമമാക്കി",
            manage: "നിയന്ത്രിക്കുക",
            signOut: "സൈൻ ഔട്ട്"
        },
        "Italian": {
            displayLanguage: "Lingua di visualizzazione",
            dashboard: "Dashboard",
            chat: "Chat",
            myAgents: "I miei agenti",
            marketplace: "Mercato",
            vendorDashboard: "Dashboard fornitore",
            billing: "Fatturazione",
            adminDashboard: "Dashboard amministratore",
            updates: "Aggiornamenti",
            helpFaq: "Aiuto e FAQ",
            logOut: "Disconnetti",
            joined: "Iscritto a dicembre 2025",
            securityBtn: "Sicurezza e linee guida",
            totalSessions: "Sessioni totali",
            proFeatures: "Funzionalità Pro",
            accountSettings: "Impostazioni account",
            credits: "Crediti",
            accountPreferences: "Preferenze account",
            timezone: "Fuso orario",
            currency: "Valuta",
            theme: "Tema",
            securityStatus: "Stato di sicurezza",
            accountSecure: "Account completamente sicuro",
            twoFactor: "Autenticazione a due fattori",
            enabled: "Abilitato",
            manage: "Gestisci",
            signOut: "Disconnetti"
        },
        "Dutch": {
            displayLanguage: "Weergavetaal",
            dashboard: "Dashboard",
            chat: "Chat",
            myAgents: "Mijn agenten",
            marketplace: "Marktplaats",
            vendorDashboard: "Leveranciersdashboard",
            billing: "Facturering",
            adminDashboard: "Beheerdersdashboard",
            updates: "Updates",
            helpFaq: "Hulp & FAQ",
            logOut: "Uitloggen",
            joined: "Lid sinds december 2025",
            securityBtn: "Beveiliging & Richtlijnen",
            totalSessions: "Totaal aantal sessies",
            proFeatures: "Pro-functies",
            accountSettings: "Accountinstellingen",
            credits: "Credits",
            accountPreferences: "Accountvoorkeuren",
            timezone: "Tijdzone",
            currency: "Valuta",
            theme: "Thema",
            securityStatus: "Beveiligingsstatus",
            accountSecure: "Account volledig beveiligd",
            twoFactor: "Tweefactorauthenticatie",
            enabled: "Ingeschakeld",
            manage: "Beheren",
            signOut: "Uitloggen"
        },
        "Urdu": {
            displayLanguage: "نمایاں زبان",
            dashboard: "ڈیش بورڈ",
            chat: "چیٹ",
            myAgents: "میرے ایجنٹس",
            marketplace: "مارکیٹ پلیس",
            vendorDashboard: "وینڈر ڈیش بورڈ",
            billing: "بلنگ",
            adminDashboard: "ایڈمن ڈیش بورڈ",
            updates: "اپ ڈیٹس",
            helpFaq: "مدد اور سوالات",
            logOut: "لاگ آؤٹ",
            joined: "دسمبر 2025 میں شامل ہوئے",
            securityBtn: "سیکیورٹی اور رہنما اصول",
            totalSessions: "کل سیشنز",
            proFeatures: "پرو خصوصیات",
            accountSettings: "اکاؤنٹ کی ترتیبات",
            credits: "کریڈٹ",
            accountPreferences: "اکاؤنٹ کی ترجیحات",
            timezone: "ٹائم زون",
            currency: "کرنسی",
            theme: "تھیم",
            securityStatus: "سیکیورٹی کی صورتحال",
            accountSecure: "اکاؤنٹ مکمل طور پر محفوظ ہے",
            twoFactor: "دو قدمی تصدیق",
            enabled: "فعال",
            manage: "انتظام کریں",
            signOut: "سائن آؤٹ"
        }
    };

    const t = (key) => {
        const langData = translations[language] || translations['English'];
        return langData[key] || translations['English'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, languages: uniqueLanguages, region, setRegion, regions, regionFlags, allTimezones, regionTimezones }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
